spring:
  application:
    name: websocket

server:
  port: 8070

logging:
  level:
    root: INFO # Sets the default logging level for the entire application
    org.springframework.web: DEBUG # Sets the logging level for Spring Web-related classes to DEBUG
    com.cdac.websocket.config: TRACE # Sets the logging level for a custom package to TRACE